//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FungeyeApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mushroom
    {
        public string Species { get; set; }
        public string CommonName { get; set; }
        public string CapChar { get; set; }
        public string NextCapChar { get; set; }
        public string CapColor { get; set; }
        public string Stem { get; set; }
        public string StemColor { get; set; }
        public string Hymenium { get; set; }
        public string Attachment { get; set; }
        public string HymeniumColor { get; set; }
        public string SporeColor { get; set; }
        public string Annulus { get; set; }
        public string Ecology { get; set; }
        public string NewEcology { get; set; }
        public string Substrate { get; set; }
        public string GrowthPattern { get; set; }
        public string NewGrowthPattern { get; set; }
        public string MushroomID { get; set; }
        public string Edibility { get; set; }
    }
}
