//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FungeyeApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserMushroom
    {
        public string PictureURL { get; set; }
        public string Address { get; set; }
        public string UserID { get; set; }
        public string MushroomID { get; set; }
        public string UserDescription { get; set; }
    
        public virtual Mushroom Mushroom { get; set; }
    }
}
